# Generated by Django 2.2.6 on 2019-10-12 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='quote_body',
            field=models.TextField(default='Test'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quote',
            name='context',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='quote',
            name='source',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
