# Generated by Django 2.2.6 on 2019-10-09 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
