# Generated by Django 2.2.6 on 2019-10-09 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20191008_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='company_email',
            field=models.EmailField(max_length=254),
        ),
    ]
